test-managment/Controllers/TestRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using test_managment.Contracts;
using test_managment.Data;
using test_managment.Models;

namespace test_managment.Controllers
{
    [Authorize]
    public class TestRequestController : Controller
    {
        private readonly ITestRequestRepository _testRequestRepo;
        private readonly ITestTypeRepository _testTypeRepo;
        private readonly ITestAllocationRepository _testAllocationRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<Patient> _userManager;

        public TestRequestController(
            ITestRequestRepository testRequestRepo,
            ITestTypeRepository testTypeRepo,
            ITestAllocationRepository testAllocationRepository,
            IMapper mapper,
            UserManager<Patient> userManager
            )
        {
            _testRequestRepo = testRequestRepo;
            _testTypeRepo = testTypeRepo;
            _testAllocationRepository = testAllocationRepository;
            _mapper = mapper;
            _userManager = userManager;
        }

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Index()
        {
            var testRequests = await _testRequestRepo.FindAll();
            var testRequestsModel = _mapper.Map<List<TestRequestVM>>(testRequests);
            var model = new AdminTestRequestViewVM
            {
                TotalRequests = testRequestsModel.Count,
                ApprovedRequests = testRequestsModel.Count(q => q.Approved == true),
                PendingRequests = testRequestsModel.Count(q => q.Approved == null),
                RejectedRequests = testRequestsModel.Count(q => q.Approved == false),
                TestRequests = testRequestsModel
            };
            return View(model);
        }

        public async Task<ActionResult> MyTest()
        {
            var patient = await _userManager.GetUserAsync(User);
            var patientId = patient.Id;
            var patientAllocations = await _testAllocationRepository.GetTestAllocationsByPatient(patientId);
            var patientRequests = await _testRequestRepo.GetTestRequestsByPatient(patientId);

            var patientAllocationsModel = _mapper.Map<List<TestAllocationVM>>(patientAllocations);
            var patientRequestsModel = _mapper.Map<List<TestRequestVM>>(patientRequests);

            var model = new PatientTestRequestViewVM
            {
                TestAllocations = patientAllocationsModel,
                TestRequests = patientRequestsModel
            };

            return View(model);
        }

        // GET: TestRequest/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var testRequest = await _testRequestRepo.FindById(id);
            var model = _mapper.Map<TestRequestVM>(testRequest);
            return View(model);
        }

        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var user = _userManager.GetUserAsync(User).Result;
                var testRequest = await _testRequestRepo.FindById(id);
                testRequest.Approved = true;
                testRequest.ApprovedById = user.Id;
                testRequest.DateActioned = DateTime.Now;

                var isSuccess = await _testRequestRepo.Update(testRequest);

                return RedirectToAction(nameof(Index));

            }
            catch ( Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
            
        }

        public async Task<ActionResult> RejectRequest(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var testRequest = await _testRequestRepo.FindById(id);
                testRequest.Approved = false;
                testRequest.ApprovedById = user.Id;
                testRequest.DateActioned = DateTime.Now;

                var isSuccess = await _testRequestRepo.Update(testRequest);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: TestRequest/Create
        public async Task<ActionResult> Create()
        {
            var testTypes = await _testTypeRepo.FindAll();
            var testTypeItems = testTypes.Select(q => new SelectListItem
            {
                Text = q.Name,
                Value = q.Id.ToString()
            });
            var model = new CreateTestRequestVM
            {
                TestTypes = testTypeItems
            };
            return View(model);
        }

        // POST: TestRequest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateTestRequestVM model)
        {
            
            try
            {
                var testTypes = await _testTypeRepo.FindAll();
                var testTypeItems = testTypes.Select(q => new SelectListItem
                {
                    Text = q.Name,
                    Value = q.Id.ToString()
                });
                model.TestTypes = testTypeItems;

                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                
                var patient = await _userManager.GetUserAsync(User);
                var allocation = await _testAllocationRepository.GetTestAllocationsByPatientAndType(patient.Id, model.TestTypeId);

                var testRequestModel = new TestRequestVM
                {
                    RequestingPatientId = patient.Id,
                    TestDate = model.TestDate,
                    Approved = null,
                    DateActioned = DateTime.Now,
                    DateRequested = DateTime.Now,
                    TestTypeId = model.TestTypeId
                };

                var testRequest = _mapper.Map<TestRequest>(testRequestModel);
                var isSuccess = await _testRequestRepo.Create(testRequest);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong");
                    return View(model);
                }

                return RedirectToAction("MyTest");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View();
            }
        }

        // GET: TestRequest/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TestRequest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TestRequest/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var testRequest = await _testRequestRepo.FindById(id);
            var isSuccess = await _testRequestRepo.Delete(testRequest);

            if (testRequest == null)
            {
                return NotFound();
            }

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction("MyTest");
        }

        // POST: TestRequest/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, TestRequestVM model)
        {
            try
            {
                var testRequest = await _testRequestRepo.FindById(id);
                var isSuccess = await _testRequestRepo.Delete(testRequest);

                if (testRequest == null)
                {
                    return NotFound();
                }

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction("MyTest");
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }
    }
}

test-managment/Controllers/TestTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using test_managment.Contracts;
using test_managment.Data;
using test_managment.Models;

namespace test_managment.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class TestTypesController : Controller
    {
        private readonly ITestTypeRepository _repo;
        private readonly IMapper _mapper;

        public TestTypesController(ITestTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        
        // GET: TestTypes
        public async Task<ActionResult> Index()
        {
            var testTypes = await _repo.FindAll();
            var model = _mapper.Map<List<TestType>, List<TestTypeVM>>(testTypes.ToList());
            return View(model);
        }

        // GET: TestTypes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var isExists = await _repo.isExists(id); 
            if (isExists)
            {
                return NotFound();
            }

            var testType = await _repo.FindById(id);
            var model = _mapper.Map<TestTypeVM>(testType);
            return View(model);
        }

        // GET: TestTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TestTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TestTypeVM model)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var testType = _mapper.Map<TestType>(model);
                testType.DateCreated = DateTime.Now;

                var isSuccess = await _repo.Create(testType);

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: TestTypes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var isExists = await _repo.isExists(id);
            if (isExists)
            {
                return NotFound();
            }
            var testType = await _repo.FindById(id);
            var model = _mapper.Map<TestTypeVM>(testType);

            return View(model);
        }

        // POST: TestTypes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TestTypeVM model)
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var testType = _mapper.Map<TestType>(model);
                var isSuccess = await _repo.Update(testType);

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: TestTypes/Delete/5
        public async Task<ActionResult> Delete(int id)
        {

            var testType = await _repo.FindById(id);
            var isSuccess = await _repo.Delete(testType);

            if (testType == null)
            {
                return NotFound();
            }

            if (!isSuccess)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: TestTypes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, TestTypeVM model)
        {
            try
            {
                // TODO: Add delete logic here
                var testType = await _repo.FindById(id);
                var isSuccess = await _repo.Delete(testType);

                if (testType == null)
                {
                    return NotFound();
                }

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }
    }
}

test-managment/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using test_managment.Data
@inject SignInManager<Patient> SignInManager
@inject UserManager<Patient> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Corona Testing Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Corona Testing Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="TestRequest" asp-action="Create">Apply for Testing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="TestRequest" asp-action="MyTest">My Tests</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="TestTypes" asp-action="Index">Test Types</a>
                                        <a class="dropdown-item" asp-controller="TestAllocation" asp-action="Index">Test Allocations</a>
                                        <a class="dropdown-item" asp-controller="TestRequest" asp-action="Index">Test Requests</a>
                                        <a class="dropdown-item" asp-controller="TestAllocation" asp-action="ListPatients">Patients</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Corona Testing Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>